"""Closed vocabularies for the grounded answering boundary."""

from enum import StrEnum


class AnswerRefusalCode(StrEnum):
    """Typed reason codes for total refusal to answer."""

    RESEARCH_REFUSED = "RESEARCH_REFUSED"
    RESEARCH_TERMINATED = "RESEARCH_TERMINATED"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    MODEL_OUTPUT_MALFORMED = "MODEL_OUTPUT_MALFORMED"
    NO_PROPOSITIONS = "NO_PROPOSITIONS"
    CITATION_SOURCE_UNKNOWN = "CITATION_SOURCE_UNKNOWN"
    CITATION_DIGEST_MISMATCH = "CITATION_DIGEST_MISMATCH"
    CITATION_PINPOINT_MISMATCH = "CITATION_PINPOINT_MISMATCH"
    CITATION_PROVISION_MISMATCH = "CITATION_PROVISION_MISMATCH"
    QUOTE_NOT_IN_SOURCE = "QUOTE_NOT_IN_SOURCE"
    ENTAILMENT_UNSUPPORTED = "ENTAILMENT_UNSUPPORTED"
    ENTAILMENT_UNAVAILABLE = "ENTAILMENT_UNAVAILABLE"
    CORPUS_UNAVAILABLE = "CORPUS_UNAVAILABLE"


class AnswerOutcome(StrEnum):
    """Audited outcome of one grounded answering evaluation."""

    ANSWERED = "ANSWERED"
    REFUSED = "REFUSED"
