"""Closed Phase 3 evidence vocabularies."""

from enum import StrEnum


class EvidenceKind(StrEnum):
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    TEXT = "TEXT"


class EvidenceRole(StrEnum):
    ORIGINAL = "ORIGINAL"
    DERIVED = "DERIVED"


class EvidenceReviewStatus(StrEnum):
    UPLOADED = "UPLOADED"
    REVIEW_ACCEPTED = "REVIEW_ACCEPTED"
    REVIEW_REJECTED = "REVIEW_REJECTED"


class EvidenceRejectionCode(StrEnum):
    TYPE_NOT_ALLOWED = "TYPE_NOT_ALLOWED"
    SIGNATURE_MALFORMED = "SIGNATURE_MALFORMED"
    DECLARED_TYPE_MISMATCH = "DECLARED_TYPE_MISMATCH"
    EXTENSION_MISMATCH = "EXTENSION_MISMATCH"
    EMPTY_INPUT = "EMPTY_INPUT"
    SIZE_LIMIT_EXCEEDED = "SIZE_LIMIT_EXCEEDED"
    UNSAFE_FILENAME = "UNSAFE_FILENAME"
    EXPECTED_SIZE_MISMATCH = "EXPECTED_SIZE_MISMATCH"
    TRUNCATED_STREAM = "TRUNCATED_STREAM"
